pipeline {
    agent any

    stages {
        stage('git check') {
            steps {
                git branch: 'main', url: 'https://github.com/u-kosmonaft-u/testrepo'
            }
        }
        stage('git clone repo') {
            steps {
                echo 'Testing..'
            }
        }
        stage('start ansible script') {
            steps {
                echo 'Deploying....'
            }
        }
    }
}