pipeline {
    agent any

    stages {
        stage('git check') {
            steps {
                git branch: 'main', url: 'https://github.com/u-kosmonaft-u/testrepo'
            }
        }
        stage('show working dir') {
            steps {
                sh 'pwd'
                sh 'ls -la'
            }
        }
        stage('run ansible build playbook') {
            steps {
                ansiblePlaybook (credentialsId: 'my-pass',
                                 installation: 'Ansible',
                                 inventory: 'ansible/inv.yml',
                                 playbook: 'ansible/buildimage.yml',
                                 colorized: true)
            }
        }
        stage('success') {
            steps {
                echo 'finally!'
            }
        }
    }
}