pipeline {
    agent any

    stages {
        stage('git check') {
            steps {
                git branch: 'main', url: 'https://github.com/u-kosmonaft-u/testrepo'
            }
        }
        stage('debug working dir') {
            steps {
                sh 'pwd'
            }
            steps {
                sh 'ls -la'
            }
        }
//         stage('run ansible playbook') {
//             steps {
//                 ansiblePlaybook credentialsId: 'my-pass', installation: 'Ansible', inventory: './ansible/inv.yml', playbook: './ansible/buildimage.yml'
//             }
//         }
        stage('success') {
            steps {
                echo 'finally!'
            }
        }
    }
}