---
- hosts: builder
  gather_facts: no
  become: yes
  become_method: sudo
  become_user: root
  tasks:

    - name: create build directory
      file:
        path: /opt/demo-dockerfile
        state: directory
        owner: root
        group: root
        mode: '0755'

    - name: copy scr dir
      copy:
        src: ../src
        dest: /opt/demo-dockerfile/src
        owner: root
        group: root
        mode: '0755'

    - name: copy Dockerfile
      copy:
        src: ../Dockerfile
        dest: /opt/demo-dockerfile/Dockerfile
        owner: root
        group: root
        mode: '0644'

    - name: build container image
      docker_image:
        name: pythondemo:v1.0
        tag: v1
        build:
          path: /opt/demo-dockerfile
        state: present
