---
- hosts: builder
  gather_facts: no
  become: yes
  become_method: sudo
  become_user: root
  tasks:
    - debug: msg="{{ lookup('env','BUILD_TAG') }}"

    - name: create build directory
      file:
        path: /opt/demo-dockerfile
        state: directory
        owner: root
        group: root
        mode: '0755'

    - name: copy scr dir
      copy:
        src: ../src
        dest: /opt/demo-dockerfile/src
        owner: root
        group: root
        mode: '0755'

    - name: copy Dockerfile
      copy:
        src: ../requirements.txt
        dest: /opt/demo-dockerfile/requirements.txt
        owner: root
        group: root
        mode: '0644'

    - name: copy Dockerfile
      copy:
        src: ../Dockerfile
        dest: /opt/demo-dockerfile/Dockerfile
        owner: root
        group: root
        mode: '0644'

    - name: build container image
      docker_image:
        name: pythondemo:"{{ lookup('env','BUILD_TAG') }}"
        tag: "{{ lookup('env','BUILD_TAG') }}"
        build:
          path: /opt/demo-dockerfile
        state: present

    - name: Tag and push to local regestry
      docker_image:
        name: pythondemo:"{{ lookup('env','BUILD_TAG') }}"
        repository: nexus.regestry.home:8083
        tag: "{{ lookup('env','BUILD_TAG') }}"
        source: local
        push: yes

    - name: Remove image from workdir
      docker_image:
        state: absent
        name: nexus.regestry.home:8083/pythondemo:"{{ lookup('env','BUILD_TAG') }}"
        tag: "{{ lookup('env','BUILD_TAG') }}"
